// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvDSlS4WRD-ovO9HXexMgMBoYyokgAyRo',
    appId: '1:238887394473:web:2b3c5f9d247768f0df5db8',
    messagingSenderId: '238887394473',
    projectId: 'madhanvasu-app',
    authDomain: 'madhanvasu-app.firebaseapp.com',
    storageBucket: 'madhanvasu-app.firebasestorage.app',
    measurementId: 'G-97HF5H8SW9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBYT32tKcgg2cmYgOv7B7pDedw6kkwHrU',
    appId: '1:238887394473:android:4d1df3f7fa2c14efdf5db8',
    messagingSenderId: '238887394473',
    projectId: 'madhanvasu-app',
    storageBucket: 'madhanvasu-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUrKj6-CGg2SS94VFc-Y2CxxNjC1SNTjc',
    appId: '1:238887394473:ios:5f3faa63acdb1803df5db8',
    messagingSenderId: '238887394473',
    projectId: 'madhanvasu-app',
    storageBucket: 'madhanvasu-app.firebasestorage.app',
    iosBundleId: 'com.example.madhanvasuApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDUrKj6-CGg2SS94VFc-Y2CxxNjC1SNTjc',
    appId: '1:238887394473:ios:5f3faa63acdb1803df5db8',
    messagingSenderId: '238887394473',
    projectId: 'madhanvasu-app',
    storageBucket: 'madhanvasu-app.firebasestorage.app',
    iosBundleId: 'com.example.madhanvasuApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAvDSlS4WRD-ovO9HXexMgMBoYyokgAyRo',
    appId: '1:238887394473:web:8e69fbd508a71145df5db8',
    messagingSenderId: '238887394473',
    projectId: 'madhanvasu-app',
    authDomain: 'madhanvasu-app.firebaseapp.com',
    storageBucket: 'madhanvasu-app.firebasestorage.app',
    measurementId: 'G-MD1PVVKR8G',
  );
}
